tesing new deploy

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -16,78 +16,82 @@ jobs:
     name: Deploy
     runs-on: ubuntu-latest
     environment: production
-
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Build, tag, and push image to Amazon ECR
-        id: build-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-
+      - name: check env variable
         run: |
-          IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}
-          # Build a docker container and
-          # push it to ECR so that it can
-          # be deployed to ECS.
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+          echo  ${{ secrets.SSH_HOST }}
 
-      - name: SSH and Deploy
-        uses: appleboy/ssh-action@v0.1.5
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: testing
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USER }}
-          key: ${{ secrets.SSH_KEY }}
-          envs: ECR_REGISTRY,ECR_REPOSITORY
-          script: |
-            IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}
-            docker stop my-app || true
-            docker rm my-app || true
-            docker run -d --name my-app -p 80:8080 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-            rm old.txt
-            mv version.txt old.txt
-            echo $IMAGE_TAG >version.txt
-      - name: send telegram message on success
-        if: success()
-        # Runs this step only if the 'deploy' job succeeded.
-        uses: appleboy/telegram-action@master
-        with:
-          to: ${{ secrets.TELEGRAM__SEND_TO }}
-          token: ${{ secrets.TELEGRAM__BOT_TOKEN }}
-          message: |
-            Deploy ${{ github.event.repository.name }} SUCCEEDED
-            ${{ github.actor }} created commit:
-            Commit message: ${{ github.event.commits[0].message }}
-            Repository: ${{ github.repository }}
-            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
+    # steps:
+    #   - name: Checkout
+    #     uses: actions/checkout@v4
 
-      - name: send telegram message on failure
-        if: failure()
-        # Runs this step only if the 'deploy' job failed.
-        uses: appleboy/telegram-action@master
-        with:
-          to: ${{ secrets.TELEGRAM__SEND_TO }}
-          token: ${{ secrets.TELEGRAM__BOT_TOKEN }}
-          message: |
-            Deploy ${{ github.event.repository.name }} FAILED
-            ${{ github.actor }} created commit:
-            Commit message: ${{ github.event.commits[0].message }}
-            Repository: ${{ github.repository }}
-            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
+    #   - name: Configure AWS credentials
+    #     uses: aws-actions/configure-aws-credentials@v1
+    #     with:
+    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #       aws-region: ${{ env.AWS_REGION }}
+
+    #   - name: Login to Amazon ECR
+    #     id: login-ecr
+    #     uses: aws-actions/amazon-ecr-login@v1
+
+    #   - name: Build, tag, and push image to Amazon ECR
+    #     id: build-image
+    #     env:
+    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+
+    #     run: |
+    #       IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}
+    #       # Build a docker container and
+    #       # push it to ECR so that it can
+    #       # be deployed to ECS.
+    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+    #       echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+
+    #   - name: SSH and Deploy
+    #     uses: appleboy/ssh-action@v0.1.5
+    #     env:
+    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+    #       ECR_REPOSITORY: testing
+    #     with:
+    #       host: ${{ secrets.SSH_HOST }}
+    #       username: ${{ secrets.SSH_USER }}
+    #       key: ${{ secrets.SSH_KEY }}
+    #       envs: ECR_REGISTRY,ECR_REPOSITORY
+    #       script: |
+    #         IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}
+    #         docker stop my-app || true
+    #         docker rm my-app || true
+    #         docker run -d --name my-app -p 80:8080 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+    #         rm old.txt
+    #         mv version.txt old.txt
+    #         echo $IMAGE_TAG >version.txt
+    #   - name: send telegram message on success
+    #     if: success()
+    #     # Runs this step only if the 'deploy' job succeeded.
+    #     uses: appleboy/telegram-action@master
+    #     with:
+    #       to: ${{ secrets.TELEGRAM__SEND_TO }}
+    #       token: ${{ secrets.TELEGRAM__BOT_TOKEN }}
+    #       message: |
+    #         Deploy ${{ github.event.repository.name }} SUCCEEDED
+    #         ${{ github.actor }} created commit:
+    #         Commit message: ${{ github.event.commits[0].message }}
+    #         Repository: ${{ github.repository }}
+    #         See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
+
+    #   - name: send telegram message on failure
+    #     if: failure()
+    #     # Runs this step only if the 'deploy' job failed.
+    #     uses: appleboy/telegram-action@master
+    #     with:
+    #       to: ${{ secrets.TELEGRAM__SEND_TO }}
+    #       token: ${{ secrets.TELEGRAM__BOT_TOKEN }}
+    #       message: |
+    #         Deploy ${{ github.event.repository.name }} FAILED
+    #         ${{ github.actor }} created commit:
+    #         Commit message: ${{ github.event.commits[0].message }}
+    #         Repository: ${{ github.repository }}
+    #         See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
